version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    command: fastapi run main.py --port 8000 --host 0.0.0.0
  frontend:
    build: .
    ports:
      - "8501:8501"
    command: streamlit run dashboard.py --server.address=0.0.0.0 --server.port=8501
    depends_on:
      - backend